### ISSUE TITLE
Language selection support is missing.

### ISSUE THREAD

**Issue by smn** [universalcore/unicore-cms-mnm#3]
![malaria_no_more___universal_core](https://cloud.githubusercontent.com/assets/1065/5643883/2614f2a4-9666-11e4-9388-00b361484195.jpg)

Completely understandable because of the initial rush. Now does need to be added. The usual approach won't work because we have 6 languages for India & the space for listing those simply isn't there.

**Comment by nathanbegbie** [comment]
@smn: I think we should deal with this before adding RTL support. Mind if I have a crack at it tomorrow morning?

**Comment by smn** [comment]
Would love it if you did

**Comment by miltontony** [comment]
Being worked in #5
